from __future__ import annotations

import re
from copy import deepcopy
from textwrap import indent

DIFFICULTIES = ["Beginner", "Average", "Expert", "God"]
DIFFICULTY_COLORS = {
    "Beginner": "#16a34a",
    "Average": "#2563eb",
    "Expert": "#7c3aed",
    "God": "#dc2626",
}


CHAPTER_BLUEPRINTS = [
    {
        "id": "chapter_1",
        "number": 1,
        "title": "Using the Python Interpreter",
        "emoji": "💻",
        "description": "Launch Python, use interactive mode, and understand script execution basics.",
        "docs_link": "https://docs.python.org/3/tutorial/interpreter.html",
        "lessons": [
            {
                "slug": "starting-python",
                "title": "Starting Python and the REPL",
                "summary": "Open Python and evaluate expressions interactively.",
                "objectives": ["Start the interpreter", "Run quick experiments", "Exit cleanly"],
                "docs_link": "https://docs.python.org/3/tutorial/interpreter.html#invoking-the-interpreter",
                "estimated_minutes": 10,
                "code": "print(2 + 2)\nname = 'Python'\nprint(f'Hello, {name}!')",
                "related_topics": ["Arguments", "Interactive mode"],
                "quiz": {"question": "What does the REPL help you do first?", "answer": "Test code interactively and get immediate feedback."},
            },
            {
                "slug": "command-line-arguments",
                "title": "Command line arguments",
                "summary": "Pass values into scripts from the terminal.",
                "objectives": ["Read argv values", "Handle missing input", "Print helpful usage"],
                "docs_link": "https://docs.python.org/3/tutorial/interpreter.html#argument-passing",
                "estimated_minutes": 12,
                "code": "import sys\nargs = sys.argv[1:]\nprint('Arguments:', args if args else ['<none>'])",
                "related_topics": ["sys module", "Modules"],
                "quiz": {"question": "Where are script arguments stored?", "answer": "In sys.argv."},
            },
            {
                "slug": "interactive-mode",
                "title": "Interactive mode features",
                "summary": "Use prompts, history, and experimentation to learn faster.",
                "objectives": ["Recognize prompts", "Reuse expressions", "Explore objects quickly"],
                "docs_link": "https://docs.python.org/3/tutorial/interpreter.html#interactive-mode",
                "estimated_minutes": 8,
                "code": "numbers = [1, 2, 3]\nlen(numbers)\nsum(numbers)",
                "related_topics": ["Built-ins", "Help system"],
                "quiz": {"question": "Why is interactive mode useful for learning?", "answer": "It shortens the feedback loop for trying small pieces of code."},
            },
        ],
    },
    {
        "id": "chapter_2",
        "number": 2,
        "title": "An Informal Introduction to Python",
        "emoji": "🐣",
        "description": "Work with numbers, strings, and the first practical Python building blocks.",
        "docs_link": "https://docs.python.org/3/tutorial/introduction.html",
        "lessons": [
            {
                "slug": "numbers-arithmetic",
                "title": "Numbers and arithmetic",
                "summary": "Use Python as a calculator with integer and floating-point expressions.",
                "objectives": ["Evaluate expressions", "Understand operator behavior", "Inspect numeric results"],
                "docs_link": "https://docs.python.org/3/tutorial/introduction.html#using-python-as-a-calculator",
                "estimated_minutes": 12,
                "code": "price = 19.99\nquantity = 3\ntotal = price * quantity\nprint(round(total, 2))",
                "related_topics": ["Division", "Formatting"],
                "quiz": {"question": "What kind of number does `/` return in Python 3?", "answer": "A floating-point value."},
            },
            {
                "slug": "strings-text",
                "title": "Strings and text",
                "summary": "Create, slice, and format text values.",
                "objectives": ["Use quotes correctly", "Slice strings", "Format output"],
                "docs_link": "https://docs.python.org/3/tutorial/introduction.html#strings",
                "estimated_minutes": 14,
                "code": "language = 'Python'\nprint(language[0:3])\nprint(f'{language} is fun to learn!')",
                "related_topics": ["Slicing", "f-strings"],
                "quiz": {"question": "What does `language[0:3]` return for `'Python'`?", "answer": "The substring `'Pyt'`."},
            },
            {
                "slug": "lists-first-look",
                "title": "Lists for the first time",
                "summary": "Store ordered collections and mutate them safely.",
                "objectives": ["Create lists", "Index elements", "Append new values"],
                "docs_link": "https://docs.python.org/3/tutorial/introduction.html#lists",
                "estimated_minutes": 12,
                "code": "tools = ['python', 'pip']\ntools.append('streamlit')\nprint(tools)\nprint(tools[-1])",
                "related_topics": ["Mutation", "Data structures"],
                "quiz": {"question": "Which method adds an item to the end of a list?", "answer": "append()"},
            },
        ],
    },
    {
        "id": "chapter_3",
        "number": 3,
        "title": "More on Control Flow",
        "emoji": "🧭",
        "description": "Choose paths, repeat work, and structure reusable behavior with functions.",
        "docs_link": "https://docs.python.org/3/tutorial/controlflow.html",
        "lessons": [
            {
                "slug": "if-statements",
                "title": "if, elif, and else",
                "summary": "Branch based on conditions and organize decision logic.",
                "objectives": ["Evaluate conditions", "Use elif chains", "Handle defaults"],
                "docs_link": "https://docs.python.org/3/tutorial/controlflow.html#if-statements",
                "estimated_minutes": 12,
                "code": "score = 82\nif score >= 90:\n    grade = 'A'\nelif score >= 75:\n    grade = 'B'\nelse:\n    grade = 'C'\nprint(grade)",
                "related_topics": ["Booleans", "Comparison operators"],
                "quiz": {"question": "When does an `else` block run?", "answer": "When every previous condition is false."},
            },
            {
                "slug": "loops-and-range",
                "title": "for loops, range, break, and continue",
                "summary": "Iterate over data and control loop execution cleanly.",
                "objectives": ["Loop over items", "Generate ranges", "Stop or skip iterations"],
                "docs_link": "https://docs.python.org/3/tutorial/controlflow.html#for-statements",
                "estimated_minutes": 14,
                "code": "for number in range(1, 6):\n    if number == 4:\n        continue\n    print(number)",
                "related_topics": ["Iteration", "Loop patterns"],
                "quiz": {"question": "What does `continue` do in a loop?", "answer": "It skips to the next iteration."},
            },
            {
                "slug": "functions-basics",
                "title": "Defining functions",
                "summary": "Package reusable logic with parameters and return values.",
                "objectives": ["Define functions", "Pass arguments", "Return results"],
                "docs_link": "https://docs.python.org/3/tutorial/controlflow.html#defining-functions",
                "estimated_minutes": 15,
                "code": "def greet(name):\n    return f'Hello, {name}!'\n\nprint(greet('Learner'))",
                "related_topics": ["Scope", "Documentation strings"],
                "quiz": {"question": "Which keyword creates a function?", "answer": "def"},
            },
        ],
    },
    {
        "id": "chapter_4",
        "number": 4,
        "title": "Data Structures",
        "emoji": "🧱",
        "description": "Master lists, tuples, sets, dictionaries, and common collection patterns.",
        "docs_link": "https://docs.python.org/3/tutorial/datastructures.html",
        "lessons": [
            {
                "slug": "lists-stack-queue",
                "title": "Lists as flexible sequences",
                "summary": "Add, remove, sort, and reuse list methods confidently.",
                "objectives": ["Use list methods", "Sort and reverse data", "Model stacks and queues"],
                "docs_link": "https://docs.python.org/3/tutorial/datastructures.html#more-on-lists",
                "estimated_minutes": 14,
                "code": "items = ['read', 'code', 'review']\nitems.append('ship')\nitems.sort()\nprint(items)",
                "related_topics": ["Mutability", "Queues"],
                "quiz": {"question": "Which method sorts a list in place?", "answer": "sort()"},
            },
            {
                "slug": "tuples-sequences",
                "title": "Tuples and sequence unpacking",
                "summary": "Use immutable groupings and unpack values clearly.",
                "objectives": ["Create tuples", "Unpack values", "Choose tuples intentionally"],
                "docs_link": "https://docs.python.org/3/tutorial/datastructures.html#tuples-and-sequences",
                "estimated_minutes": 10,
                "code": "point = (3, 5)\nx, y = point\nprint(x, y)",
                "related_topics": ["Immutability", "Packing"],
                "quiz": {"question": "Why choose a tuple over a list?", "answer": "To represent a fixed, immutable sequence."},
            },
            {
                "slug": "sets-dictionaries",
                "title": "Sets and dictionaries",
                "summary": "Work with unique items and key-value mappings.",
                "objectives": ["Create sets", "Look up dict values", "Iterate key-value pairs"],
                "docs_link": "https://docs.python.org/3/tutorial/datastructures.html#dictionaries",
                "estimated_minutes": 16,
                "code": "inventory = {'apples': 4, 'bananas': 6}\ninventory['oranges'] = 3\nfor item, count in inventory.items():\n    print(item, count)",
                "related_topics": ["Hashing", "Membership checks"],
                "quiz": {"question": "What does a set guarantee about its elements?", "answer": "They are unique."},
            },
        ],
    },
    {
        "id": "chapter_5",
        "number": 5,
        "title": "Modules",
        "emoji": "📦",
        "description": "Split code into files, import functionality, and explore module namespaces.",
        "docs_link": "https://docs.python.org/3/tutorial/modules.html",
        "lessons": [
            {
                "slug": "importing-modules",
                "title": "Importing modules",
                "summary": "Reuse functionality from the standard library and your own files.",
                "objectives": ["Use import", "Call imported functions", "Read module names"],
                "docs_link": "https://docs.python.org/3/tutorial/modules.html#more-on-modules",
                "estimated_minutes": 10,
                "code": "import math\nprint(math.sqrt(81))\nprint(math.pi)",
                "related_topics": ["Namespaces", "Standard library"],
                "quiz": {"question": "Why import a module?", "answer": "To reuse code without rewriting it."},
            },
            {
                "slug": "from-import",
                "title": "from imports and module search paths",
                "summary": "Control what you import and understand where Python looks for code.",
                "objectives": ["Use from imports", "Avoid namespace confusion", "Inspect search paths"],
                "docs_link": "https://docs.python.org/3/tutorial/modules.html#the-module-search-path",
                "estimated_minutes": 12,
                "code": "from pathlib import Path\nproject_root = Path('.').resolve()\nprint(project_root.name)",
                "related_topics": ["sys.path", "Imports"],
                "quiz": {"question": "Which object lists module search locations?", "answer": "sys.path"},
            },
            {
                "slug": "dir-and-main",
                "title": "Exploring modules with dir() and __main__",
                "summary": "Inspect module contents and run files directly.",
                "objectives": ["Use dir()", "Understand __main__", "Design runnable scripts"],
                "docs_link": "https://docs.python.org/3/tutorial/modules.html#executing-modules-as-scripts",
                "estimated_minutes": 12,
                "code": "def describe(name):\n    return f'Module demo for {name}'\n\nif __name__ == '__main__':\n    print(describe('Python Tutor'))",
                "related_topics": ["Script entrypoints", "Introspection"],
                "quiz": {"question": "When does `if __name__ == '__main__'` run?", "answer": "When the file is executed as a script."},
            },
        ],
    },
    {
        "id": "chapter_6",
        "number": 6,
        "title": "Input and Output",
        "emoji": "📝",
        "description": "Format data for people, accept input, and persist text with files.",
        "docs_link": "https://docs.python.org/3/tutorial/inputoutput.html",
        "lessons": [
            {
                "slug": "formatted-output",
                "title": "Formatted string output",
                "summary": "Present data clearly with f-strings and formatting tools.",
                "objectives": ["Format numbers", "Align values", "Build readable output"],
                "docs_link": "https://docs.python.org/3/tutorial/inputoutput.html#formatted-string-literals",
                "estimated_minutes": 10,
                "code": "name = 'Ada'\nscore = 98.456\nprint(f'{name:<10} | {score:.1f}')",
                "related_topics": ["repr", "str"],
                "quiz": {"question": "What does `:.1f` do in an f-string?", "answer": "It formats a float with one decimal place."},
            },
            {
                "slug": "reading-user-input",
                "title": "Reading user input",
                "summary": "Collect text input and convert it into useful values.",
                "objectives": ["Read input", "Convert types", "Handle invalid assumptions"],
                "docs_link": "https://docs.python.org/3/tutorial/inputoutput.html#reading-and-writing-files",
                "estimated_minutes": 12,
                "code": "raw_age = '21'\nage = int(raw_age)\nprint(age + 1)",
                "related_topics": ["Casting", "Validation"],
                "quiz": {"question": "Why convert input values?", "answer": "Because input returns text, and many operations need other types."},
            },
            {
                "slug": "files-basics",
                "title": "Working with files",
                "summary": "Open, read, and write files using context managers.",
                "objectives": ["Open files", "Use with blocks", "Read and write text safely"],
                "docs_link": "https://docs.python.org/3/tutorial/inputoutput.html#reading-and-writing-files",
                "estimated_minutes": 15,
                "code": "from pathlib import Path\npath = Path('notes.txt')\npath.write_text('python tutor app', encoding='utf-8')\nprint(path.read_text(encoding='utf-8'))",
                "related_topics": ["Pathlib", "Encoding"],
                "quiz": {"question": "Why use `with open(...)` or Path helpers?", "answer": "They manage file resources cleanly and reduce leaks."},
            },
        ],
    },
    {
        "id": "chapter_7",
        "number": 7,
        "title": "Errors and Exceptions",
        "emoji": "🚨",
        "description": "Read tracebacks, handle failures, and raise meaningful exceptions.",
        "docs_link": "https://docs.python.org/3/tutorial/errors.html",
        "lessons": [
            {
                "slug": "reading-tracebacks",
                "title": "Reading syntax errors and tracebacks",
                "summary": "Interpret Python error output so you can debug faster.",
                "objectives": ["Read file locations", "Spot the failing line", "Use errors as feedback"],
                "docs_link": "https://docs.python.org/3/tutorial/errors.html#syntax-errors",
                "estimated_minutes": 10,
                "code": "numbers = [1, 2, 3]\nprint(numbers[0])\n# Try changing the index to 10 to trigger an IndexError.",
                "related_topics": ["Debugging", "Indexing"],
                "quiz": {"question": "What part of a traceback often tells you where to start?", "answer": "The most recent frame and error message."},
            },
            {
                "slug": "handling-exceptions",
                "title": "Handling exceptions with try/except",
                "summary": "Catch expected failures and keep programs user-friendly.",
                "objectives": ["Use try/except", "Catch specific exceptions", "Keep recovery focused"],
                "docs_link": "https://docs.python.org/3/tutorial/errors.html#handling-exceptions",
                "estimated_minutes": 14,
                "code": "values = ['10', 'oops']\nfor value in values:\n    try:\n        print(100 / int(value))\n    except ValueError:\n        print('Please provide a valid integer.')",
                "related_topics": ["Validation", "Control flow"],
                "quiz": {"question": "Why catch specific exceptions instead of every error?", "answer": "It avoids hiding unrelated bugs."},
            },
            {
                "slug": "raising-cleanup",
                "title": "Raising exceptions and cleanup",
                "summary": "Signal invalid states and always release resources.",
                "objectives": ["Raise errors intentionally", "Use finally", "Communicate failures well"],
                "docs_link": "https://docs.python.org/3/tutorial/errors.html#defining-clean-up-actions",
                "estimated_minutes": 12,
                "code": "def set_percentage(value):\n    if not 0 <= value <= 100:\n        raise ValueError('percentage must be between 0 and 100')\n    return value\n\nprint(set_percentage(75))",
                "related_topics": ["finally", "APIs"],
                "quiz": {"question": "When should you raise an exception yourself?", "answer": "When invalid input or state should stop normal processing."},
            },
        ],
    },
    {
        "id": "chapter_8",
        "number": 8,
        "title": "Classes",
        "emoji": "🏗️",
        "description": "Model state and behavior with classes, instances, and inheritance.",
        "docs_link": "https://docs.python.org/3/tutorial/classes.html",
        "lessons": [
            {
                "slug": "class-basics",
                "title": "Defining classes and instances",
                "summary": "Create objects that bundle data and behavior together.",
                "objectives": ["Define a class", "Initialize objects", "Read attributes"],
                "docs_link": "https://docs.python.org/3/tutorial/classes.html#a-first-look-at-classes",
                "estimated_minutes": 14,
                "code": "class Learner:\n    def __init__(self, name):\n        self.name = name\n\nstudent = Learner('Maya')\nprint(student.name)",
                "related_topics": ["Attributes", "Constructors"],
                "quiz": {"question": "What method usually initializes a new object?", "answer": "__init__"},
            },
            {
                "slug": "methods-and-state",
                "title": "Instance methods and object state",
                "summary": "Use methods to update and expose object behavior.",
                "objectives": ["Write methods", "Use self", "Change object state"],
                "docs_link": "https://docs.python.org/3/tutorial/classes.html#class-and-instance-variables",
                "estimated_minutes": 14,
                "code": "class Tracker:\n    def __init__(self):\n        self.count = 0\n\n    def mark_done(self):\n        self.count += 1\n        return self.count\n\ntracker = Tracker()\nprint(tracker.mark_done())",
                "related_topics": ["Mutation", "Encapsulation"],
                "quiz": {"question": "What does `self` refer to inside an instance method?", "answer": "The specific object the method was called on."},
            },
            {
                "slug": "inheritance",
                "title": "Inheritance and customization",
                "summary": "Reuse parent behavior and specialize child classes.",
                "objectives": ["Extend a base class", "Override methods", "Reuse shared logic"],
                "docs_link": "https://docs.python.org/3/tutorial/classes.html#inheritance",
                "estimated_minutes": 16,
                "code": "class Lesson:\n    def label(self):\n        return 'General lesson'\n\nclass QuizLesson(Lesson):\n    def label(self):\n        return 'Lesson with quiz'\n\nprint(QuizLesson().label())",
                "related_topics": ["Polymorphism", "super()"],
                "quiz": {"question": "Why use inheritance?", "answer": "To share common behavior while customizing differences."},
            },
        ],
    },
    {
        "id": "chapter_9",
        "number": 9,
        "title": "Standard Library Overview",
        "emoji": "🗃️",
        "description": "Get familiar with batteries-included modules for common Python tasks.",
        "docs_link": "https://docs.python.org/3/tutorial/stdlib.html",
        "lessons": [
            {
                "slug": "os-and-glob",
                "title": "Operating system interfaces and file matching",
                "summary": "Use os, shutil, and glob-like tools to work with the environment.",
                "objectives": ["Inspect directories", "Work with paths", "Find files"],
                "docs_link": "https://docs.python.org/3/tutorial/stdlib.html#operating-system-interface",
                "estimated_minutes": 12,
                "code": "from pathlib import Path\nfor path in Path('.').glob('*.py'):\n    print(path.name)",
                "related_topics": ["pathlib", "Files"],
                "quiz": {"question": "Which module family helps you work with file paths?", "answer": "os/pathlib."},
            },
            {
                "slug": "math-and-random",
                "title": "Math, random, and statistics helpers",
                "summary": "Reach for standard library modules instead of reinventing common utilities.",
                "objectives": ["Use math", "Generate random values", "Summarize data"],
                "docs_link": "https://docs.python.org/3/tutorial/stdlib.html#mathematics",
                "estimated_minutes": 12,
                "code": "import random\nvalues = [random.randint(1, 10) for _ in range(5)]\nprint(values)\nprint(sum(values) / len(values))",
                "related_topics": ["statistics", "Reproducibility"],
                "quiz": {"question": "Why prefer the standard library for common utilities?", "answer": "It is tested, documented, and already available."},
            },
            {
                "slug": "internet-and-dates",
                "title": "Dates, compression, and internet access overview",
                "summary": "Survey modules for time, archives, and network tasks.",
                "objectives": ["Work with dates", "Recognize archive tools", "Know where to look next"],
                "docs_link": "https://docs.python.org/3/tutorial/stdlib.html#dates-and-times",
                "estimated_minutes": 14,
                "code": "from datetime import date, timedelta\ntoday = date.today()\nprint(today.isoformat())\nprint((today + timedelta(days=7)).isoformat())",
                "related_topics": ["urllib", "zipfile"],
                "quiz": {"question": "Which module is commonly used for date arithmetic?", "answer": "datetime."},
            },
        ],
    },
    {
        "id": "chapter_10",
        "number": 10,
        "title": "Brief Tour of the Standard Library",
        "emoji": "🧰",
        "description": "Explore deeper standard-library tools for quality, diagnostics, and productivity.",
        "docs_link": "https://docs.python.org/3/tutorial/stdlib2.html",
        "lessons": [
            {
                "slug": "output-formatting-tools",
                "title": "Pretty printing, templating, and text wrapping",
                "summary": "Improve readability with richer output tools.",
                "objectives": ["Format nested data", "Wrap text", "Reuse output templates"],
                "docs_link": "https://docs.python.org/3/tutorial/stdlib2.html#output-formatting",
                "estimated_minutes": 12,
                "code": "from pprint import pprint\nreport = {'module': 'Classes', 'completed': 2, 'remaining': 1}\npprint(report)",
                "related_topics": ["textwrap", "string.Template"],
                "quiz": {"question": "Why use pprint?", "answer": "To display nested data structures more readably."},
            },
            {
                "slug": "testing-and-debugging",
                "title": "Testing, logging, and debugging tools",
                "summary": "Use built-in modules to validate behavior and investigate issues.",
                "objectives": ["Read unittest patterns", "Understand logging", "Use debugging helpers"],
                "docs_link": "https://docs.python.org/3/tutorial/stdlib2.html#quality-control",
                "estimated_minutes": 15,
                "code": "import logging\nlogging.basicConfig(level=logging.INFO)\nlogging.info('Python Tutor App started')",
                "related_topics": ["doctest", "unittest"],
                "quiz": {"question": "What problem does logging solve better than print?", "answer": "Structured, configurable runtime diagnostics."},
            },
            {
                "slug": "performance-and-batteries",
                "title": "Performance measurement and useful batteries",
                "summary": "Survey modules for timing, weak references, and productivity helpers.",
                "objectives": ["Measure runtime", "Know optimization tools", "Find utility modules"],
                "docs_link": "https://docs.python.org/3/tutorial/stdlib2.html#performance-measurement",
                "estimated_minutes": 13,
                "code": "from timeit import timeit\nresult = timeit('sum(range(100))', number=1000)\nprint(round(result, 4))",
                "related_topics": ["timeit", "collections"],
                "quiz": {"question": "Which module helps time small snippets reliably?", "answer": "timeit."},
            },
        ],
    },
    {
        "id": "chapter_11",
        "number": 11,
        "title": "Virtual Environments and Packages",
        "emoji": "🌐",
        "description": "Isolate dependencies, install packages, and manage Python project environments.",
        "docs_link": "https://docs.python.org/3/tutorial/venv.html",
        "lessons": [
            {
                "slug": "why-venv",
                "title": "Why virtual environments matter",
                "summary": "Keep project dependencies isolated and reproducible.",
                "objectives": ["Explain isolation", "Create a venv", "Activate it conceptually"],
                "docs_link": "https://docs.python.org/3/tutorial/venv.html#introduction",
                "estimated_minutes": 10,
                "code": "project_name = 'python-tutor-app'\nprint(f'Use a virtual environment for {project_name}')",
                "related_topics": ["Dependencies", "Reproducibility"],
                "quiz": {"question": "Why use a virtual environment?", "answer": "To isolate project-specific packages from the global Python install."},
            },
            {
                "slug": "pip-and-packages",
                "title": "Installing packages with pip",
                "summary": "Add third-party tools safely and predictably.",
                "objectives": ["Install packages", "Read dependency names", "Use requirement files"],
                "docs_link": "https://docs.python.org/3/tutorial/venv.html#managing-packages-with-pip",
                "estimated_minutes": 12,
                "code": "requirements = ['streamlit==1.63.0']\nfor requirement in requirements:\n    print('Install with pip:', requirement)",
                "related_topics": ["requirements.txt", "Version pinning"],
                "quiz": {"question": "What file commonly pins Python dependencies?", "answer": "requirements.txt"},
            },
            {
                "slug": "sharing-environments",
                "title": "Sharing and maintaining environments",
                "summary": "Capture dependencies and onboard new contributors consistently.",
                "objectives": ["Freeze dependencies", "Document setup", "Keep environments tidy"],
                "docs_link": "https://docs.python.org/3/tutorial/venv.html#managing-packages-with-pip",
                "estimated_minutes": 10,
                "code": "commands = ['python -m venv .venv', 'source .venv/bin/activate', 'pip install -r requirements.txt']\nfor command in commands:\n    print(command)",
                "related_topics": ["Onboarding", "Project setup"],
                "quiz": {"question": "Why share setup commands with a project?", "answer": "So others can recreate the same environment quickly."},
            },
        ],
    },
]


def _difficulty_content(title: str, summary: str, objectives: list[str], code: str, related_topics: list[str]) -> dict[str, dict[str, str]]:
    wrapped_code = indent(code, "    ")
    identifier = re.sub(r"_+", "_", re.sub(r"[^a-z0-9_]+", "_", title.lower())).strip("_")
    return {
        "Beginner": {
            "explanation": f"Start with the core idea: {summary} Focus first on {objectives[0].lower()}. Read the example top to bottom and confirm what each line prints or changes.",
            "code": code,
        },
        "Average": {
            "explanation": f"At this level, connect the syntax to a practical workflow. Use this lesson to practice {objectives[0].lower()} and {objectives[1].lower()}. Try one small variation before moving on.",
            "code": f"# Average-level walkthrough for {title}\n{code}\nprint('Try changing one input to see a different result.')",
        },
        "Expert": {
            "explanation": f"Think in patterns, not just syntax. This lesson is about {summary.lower()} while balancing {objectives[1].lower()} and {objectives[2].lower()}. Ask what edge cases and invariants matter.",
            "code": f"def run_demo():\n{wrapped_code}\n\nrun_demo()\nprint('Related topics:', {related_topics!r})",
        },
        "God": {
            "explanation": f"Treat this topic as a reusable mental model. Beyond the syntax, reason about trade-offs, failure modes, and composition with adjacent concepts like {', '.join(related_topics)}.",
            "code": f"def audit_{identifier}():\n{wrapped_code}\n    return 'Reflect on trade-offs and edge cases.'\n\nprint(audit_{identifier}())",
        },
    }


def _build_chapter(chapter: dict) -> dict:
    built_lessons = []
    for position, lesson in enumerate(chapter["lessons"], start=1):
        difficulty_content = _difficulty_content(
            lesson["title"],
            lesson["summary"],
            lesson["objectives"],
            lesson["code"],
            lesson["related_topics"],
        )
        built_lessons.append(
            {
                "id": f"{chapter['id']}__{lesson['slug']}",
                "slug": lesson["slug"],
                "number": position,
                "title": lesson["title"],
                "summary": lesson["summary"],
                "objectives": lesson["objectives"],
                "docs_link": lesson["docs_link"],
                "estimated_minutes": lesson["estimated_minutes"],
                "related_topics": lesson["related_topics"],
                "quiz": lesson["quiz"],
                "difficulty_content": difficulty_content,
            }
        )

    total_minutes = sum(lesson["estimated_minutes"] for lesson in built_lessons)
    overview = (
        f"{chapter['title']} introduces {chapter['description'].lower()} "
        f"This module contains {len(built_lessons)} lessons with a combined estimated time of {total_minutes} minutes."
    )
    return {
        "id": chapter["id"],
        "number": chapter["number"],
        "title": chapter["title"],
        "emoji": chapter["emoji"],
        "description": chapter["description"],
        "overview": overview,
        "docs_link": chapter["docs_link"],
        "lessons": built_lessons,
        "lesson_count": len(built_lessons),
        "estimated_minutes": total_minutes,
    }


def get_chapters() -> list[dict]:
    return [_build_chapter(deepcopy(chapter)) for chapter in CHAPTER_BLUEPRINTS]
